name: CI Check
on:
    pull_request:

jobs:
    symfony:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@2.23.0
              with:
                  php-version: 8.1
                  tools: composer
            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-
            - uses: ramsey/composer-install@v2
            - name: Run PhpCs
              run: vendor/bin/phpcs
            - name: Run PhpStan
              run: vendor/bin/phpstan analyze --no-progress --no-interaction --error-format=github
            - name: Run PhpMd
              run: vendor/bin/phpmd src text phpmd.xml
            - name: Run rector
              run: vendor/bin/rector --dry-run --no-progress-bar
            - uses: php-actions/phpunit@v3
              with:
                  bootstrap: tests/bootstrap.php
                  configuration: phpunit.xml.dist
                  php_extensions: xdebug
                  args: --coverage-clover ./coverage.xml
              env:
                  XDEBUG_MODE: coverage