name: CI Check
on:
    pull_request:
        paths:
            - "**.php"
            - "phpcs.xml"
            - ".github/workflows/main.yml"

jobs:
    symfony:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@2.23.0
              with:
                  php-version: 8.1
                  tools: composer
            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-
            - uses: ramsey/composer-install@v2
            - uses: tinovyatkin/action-php-codesniffer@v1
            - uses: php-actions/phpstan@v3
            - name: Run PhpMd
              run: vendor/bin/phpmd src text phpmd.xml
            - uses: zingimmick/rector-action@0.0.2
              with:
                  args: --dry-run
            - uses: php-actions/phpunit@v3
              with:
                  bootstrap: tests/bootstrap.php
                  configuration: phpunit.xml.dist
                  php_extensions: xdebug
                  args: --coverage-clover ./coverage.xml
              env:
                  XDEBUG_MODE: coverage